[mgr]
keymap = [
	{ on = [ "<Esc>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = [ "q" ],     run = "quit",               desc = "Exit the process" },
	{ on = [ "Q" ],     run = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },
	{ on = [ "<C-q>" ], run = "close",              desc = "Close the current tab, or quit if it is last tab" },

	# Navigation
	{ on = [ "<Up>" ],    run = "arrow -1",   desc = "Move cursor up" },
	{ on = [ "<Down>" ],  run = "arrow 1",    desc = "Move cursor down" },
	{ on = [ "<C-u>" ],   run = "arrow -50%", desc = "Move cursor up half page" },
	{ on = [ "<C-d>" ],   run = "arrow 50%",  desc = "Move cursor down half page" },
	{ on = [ "<Left>" ],  run = "leave",      desc = "Go back to the parent directory" },
	{ on = [ "<Right>" ], run = "enter",      desc = "Enter the child directory" },
	{ on = [ "g", "g" ],  run = "arrow top",  desc = "Move cursor to the top" },
	{ on = [ "G" ],       run = "arrow bot",  desc = "Move cursor to the bottom" },

	{ on = [ "o" ],  run = "arrow -1",   desc = "Move cursor up" },
	{ on = [ "a" ],  run = "arrow 1",    desc = "Move cursor down" },
	{ on = [ "h" ],  run = "leave",      desc = "Go back to the parent directory" },
	{ on = [ "e" ],  run = "enter",      desc = "Enter the child directory" },

	# Selection
	{ on = [ "<Space>" ], run = [ "toggle --state=none", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = [ "v" ],       run = "visual_mode",                        desc = "Enter visual mode (selection mode)" },
	{ on = [ "V" ],       run = "visual_mode --unset",                desc = "Enter visual mode (unset mode)" },
	{ on = [ "<C-a>" ],   run = "toggle_all --state=true",            desc = "Select all files" },
	{ on = [ "<C-r>" ],   run = "toggle_all --state=none",            desc = "Inverse selection of all files" },

	# Operation
	{ on = [ "<Enter>" ],   run = "open",                   desc = "Open the selected files" },
	{ on = [ "O" ],         run = "open --interactive",     desc = "Open the selected files interactively" },
	{ on = [ "y" ],         run = "yank",                   desc = "Copy the selected files" },
	{ on = [ "x" ],         run = "yank --cut",             desc = "Cut the selected files" },
	{ on = [ "p" ],         run = "paste",                  desc = "Paste the files" },
	{ on = [ "P" ],         run = "paste --force",          desc = "Paste the files (overwrite if the destination exists)" },
	{ on = [ "D" ],         run = "remove --permanently",   desc = "Permanently delete the files" },
	{ on = [ "A" ],         run = "create",                 desc = "Create a file or directory (ends with / for directories)" },
	{ on = [ "r" ],         run = "rename",                 desc = "Rename a file or directory" },
	{ on = [ "R" ],         run = "rename --empty=stem --cursor=start", desc = "Rename a file or directory" },
	{ on = [ ";" ],         run = "shell --interactive",          desc = "Run a shell command" },
	{ on = [ ":" ],         run = "shell --interactive --block",  desc = "Run a shell command (block the UI until the command finishes)" },
	{ on = [ "." ],         run = "hidden toggle",          desc = "Toggle the visibility of hidden files" },
	{ on = [ "s" ],         run = "search fd",              desc = "Search files by name using fd" },
	{ on = [ "S" ],         run = "search rg",              desc = "Search files by content using ripgrep" },
	{ on = [ "f" ],         run = "plugin fzf",             desc = "Jump to a directory, or reveal a file using fzf" },

    # Sorting
	{ on = [ ",", "S" ], run = [ "sort size --reverse=no", "linemode size" ],   desc = "Sort by size" },
	{ on = [ ",", "s" ], run = [ "sort size --reverse", "linemode size" ],      desc = "Sort by size (reverse)" },

	# Copy
	{ on = [ "c", "c" ], run = "copy path",             desc = "Copy the absolute path" },
	{ on = [ "c", "d" ], run = "copy dirname",          desc = "Copy the path of the parent directory" },
	{ on = [ "c", "f" ], run = "copy filename",         desc = "Copy the name of the file" },
	{ on = [ "c", "n" ], run = "copy name_without_ext", desc = "Copy the name of the file without the extension" },

	# Find
	{ on = [ "/" ], run = "find --smart" },
	{ on = [ "?" ], run = "find --previous --smart" },
	{ on = [ "n" ], run = "find_arrow" },
	{ on = [ "N" ], run = "find_arrow --previous" },

	# Tabs
	{ on = [ "t" ], run = "tab_create --current",     desc = "Create a new tab using the current path" },
	{ on = [ "<" ], run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
	{ on = [ ">" ], run = "tab_switch 1 --relative",  desc = "Switch to the next tab" },

	# Tasks
	{ on = [ "w" ], run = "tasks_show", desc = "Show the tasks manager" },

	# Goto
	{ on = [ "g", "h" ],       run = "cd ~",             desc = "Go to the home directory" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",     desc = "Go to the config directory" },
	{ on = [ "g", "d" ],       run = "cd ~/downloads",   desc = "Go to the downloads directory" },
	{ on = [ "g", "w" ],       run = "cd ~/work",        desc = "Go to the work directory" },
	{ on = [ "g", "p" ],       run = "cd ~/projects",    desc = "Go to the projects directory" },
	{ on = [ "g", "t" ],       run = "cd /tmp",          desc = "Go to the temporary directory" },
	{ on = [ "F" ],            run = "cd --interactive", desc = "Go to a directory interactively" },
]

[tasks]
keymap = [
	{ on = [ "<Esc>" ], run = "close", desc = "Hide the task manager" },

	{ on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<Enter>" ], run = "inspect", desc = "Inspect the task" },
	{ on = [ "x" ],       run = "cancel",  desc = "Cancel the task" },
]

[select]
keymap = [
	{ on = [ "<Esc>" ],   run = "close",          desc = "Cancel selection" },
	{ on = [ "<Enter>" ], run = "close --submit", desc = "Submit the selection" },
	{ on = [ "<Up>" ],    run = "arrow -1",       desc = "Move cursor up" },
	{ on = [ "<Down>" ],  run = "arrow 1",        desc = "Move cursor down" },
]

[input]
keymap = [
	{ on = [ "<C-q>" ],       run = "close",          desc = "Cancel input" },
	{ on = [ "<Enter>" ],     run = "close --submit", desc = "Submit the input" },
	{ on = [ "<Esc>" ],       run = "escape",         desc = "Go back the normal mode, or cancel input" },

	# Mode
	{ on = [ "i" ], run = "insert",                              desc = "Enter insert mode" },
	{ on = [ "a" ], run = "insert --append",                     desc = "Enter append mode" },
	{ on = [ "v" ], run = "visual",                              desc = "Enter visual mode" },
	{ on = [ "V" ], run = [ "move -999", "visual", "move 999" ], desc = "Enter visual mode and select all" },

	# Navigation
	{ on = [ "0" ], run = "move -999",                       desc = "Move to the BOL" },
	{ on = [ "$" ], run = "move 999",                        desc = "Move to the EOL" },
	{ on = [ "I" ], run = [ "move -999", "insert" ],         desc = "Move to the BOL, and enter insert mode" },
	{ on = [ "A" ], run = [ "move 999", "insert --append" ], desc = "Move to the EOL, and enter append mode" },

	{ on = [ "<Left>" ],  run = "move -1", desc = "Move cursor left" },
	{ on = [ "<Right>" ], run = "move 1",  desc = "Move cursor right" },

	{ on = [ "b" ], run = "backward",              desc = "Move to the beginning of the previous word" },
	{ on = [ "w" ], run = "forward",               desc = "Move to the beginning of the next word" },
	{ on = [ "e" ], run = "forward --end-of-word", desc = "Move to the end of the next word" },

	# Deletion
	{ on = [ "d" ], run = "delete --cut",                              desc = "Cut the selected characters" },
	{ on = [ "D" ], run = [ "delete --cut", "move 999" ],              desc = "Cut until the EOL" },
	{ on = [ "c" ], run = "delete --cut --insert",                     desc = "Cut the selected characters, and enter insert mode" },
	{ on = [ "C" ], run = [ "delete --cut --insert", "move 999" ],     desc = "Cut until the EOL, and enter insert mode" },
	{ on = [ "x" ], run = [ "delete --cut", "move 1 --in-operating" ], desc = "Cut the current character" },
    { on = [ "<Backspace>" ], run = "backspace" },

	# Yank/Paste
	{ on = [ "y" ], run = "yank",           desc = "Copy the selected characters" },
	{ on = [ "p" ], run = "paste",          desc = "Paste the copied characters after the cursor" },
	{ on = [ "P" ], run = "paste --before", desc = "Paste the copied characters before the cursor" },

	# Undo/Redo
	{ on = [ "u" ],     run = "undo", desc = "Undo the last operation" },
	{ on = [ "<C-r>" ], run = "redo", desc = "Redo the last operation" },
]
