[tab]
active    = { fg = "#1E2031", bg = "#80AEFA" }
inactive  = { fg = "#C8D3F8", bg = "#484D66" }
max_width = 1

[status]
separator_open  = ""
separator_close = ""
mode_normal = { bg = "#161616", bold = false }
mode_select = { bg = "#202020", bold = false }
mode_unset  = { bg = "#202020", bold = false }

progress_label  = { bold = false }
progress_normal = { fg = "blue" }
progress_error  = { fg = "red" }

[mgr]
cwd  = { fg = "#888899", italic = true }
border_style  = { fg = "#282828" }

[filetype]
rules = [
	{ mime = "image/*", fg = "#a694f2" },
	{ mime = "video/*", fg = "#ffc870" },
	{ mime = "audio/*", fg = "#ffc870" },

	# Archives
	{ mime = "application/zip", fg = "#CD9EFC" },
	{ mime = "application/gzip", fg = "#CD9EFC" },
	{ mime = "application/x-tar", fg = "#CD9EFC" },
	{ mime = "application/x-bzip", fg = "#CD9EFC" },
	{ mime = "application/x-bzip2", fg = "#CD9EFC" },
	{ mime = "application/x-7z-compressed", fg = "#CD9EFC" },
	{ mime = "application/x-rar", fg = "#CD9EFC" },

	# Fallback
	{ url = "*", fg = "#fcf6f2" },
	{ url = "*/", fg = "#eeeeee" }
]

[icon]
globs = [
	{ url = "*/", fg = "#67a2fd", text = "ï„•", },
]
